using FluentValidation;using MediatR;using RevenuUsage.Domain.Entities;using RevenuUsage.Domain.Interfaces;namespace RevenuUsage.Application.Features.ReservesAndObligations;
public record GetReservesQuery(DateTime? StartDate,DateTime? EndDate):IRequest<IReadOnlyList<ReserveSnapshot>>;public record CreateReserveCommand(DateTime ReserveDate,decimal GoldValue,decimal CashInHand,decimal Deposits,string? Notes,string CreatedBy):IRequest<Guid>;public record DeleteReserveCommand(Guid Id,string Actor):IRequest;
public record GetObligationsQuery(bool ActiveOnly=true,string? ClientType=null):IRequest<IReadOnlyList<Obligation>>;public record CreateObligationCommand(DateTime ObligationDate,string? ClientName,Guid CurrencyId,decimal TotalAmount,DateTime? DueDate,string? ReferenceNo,string? Notes,string CreatedBy,string ClientType=ObligationClientTypes.Other,Guid? BankId=null,Guid? CompanyId=null):IRequest<Guid>;public record DeleteObligationCommand(Guid Id,string Actor):IRequest;
public sealed class ReservesObligationsHandler:IRequestHandler<GetReservesQuery,IReadOnlyList<ReserveSnapshot>>,IRequestHandler<CreateReserveCommand,Guid>,IRequestHandler<DeleteReserveCommand>,IRequestHandler<GetObligationsQuery,IReadOnlyList<Obligation>>,IRequestHandler<CreateObligationCommand,Guid>,IRequestHandler<DeleteObligationCommand>{private readonly IReserveRepository _reserves;private readonly IObligationRepository _obligations;public ReservesObligationsHandler(IReserveRepository r,IObligationRepository o)=>(_reserves,_obligations)=(r,o);public async Task<IReadOnlyList<ReserveSnapshot>>Handle(GetReservesQuery r,CancellationToken ct)=>(await _reserves.GetAsync(r.StartDate,r.EndDate,ct)).ToList();public Task<Guid>Handle(CreateReserveCommand r,CancellationToken ct)=>_reserves.CreateAsync(new ReserveSnapshot{ReserveDate=r.ReserveDate,GoldValue=r.GoldValue,CashInHand=r.CashInHand,Deposits=r.Deposits,Notes=r.Notes},r.CreatedBy,ct);public Task Handle(DeleteReserveCommand r,CancellationToken ct)=>_reserves.DeleteAsync(r.Id,r.Actor,ct);public async Task<IReadOnlyList<Obligation>>Handle(GetObligationsQuery r,CancellationToken ct)=>(await _obligations.GetObligationsAsync(r.ActiveOnly,r.ClientType,ct)).ToList();public Task<Guid>Handle(CreateObligationCommand r,CancellationToken ct)=>_obligations.CreateObligationAsync(new Obligation{ObligationDate=r.ObligationDate,ClientName=r.ClientName?.Trim()??string.Empty,ClientType=r.ClientType,BankId=r.ClientType==ObligationClientTypes.Bank?r.BankId:null,CompanyId=r.ClientType==ObligationClientTypes.Company?r.CompanyId:null,CurrencyId=r.CurrencyId,TotalAmount=r.TotalAmount,DueDate=r.DueDate,ReferenceNo=r.ReferenceNo,Notes=r.Notes},r.CreatedBy,ct);public Task Handle(DeleteObligationCommand r,CancellationToken ct)=>_obligations.DeleteObligationAsync(r.Id,r.Actor,ct);}
public sealed class CreateReserveValidator:AbstractValidator<CreateReserveCommand>{public CreateReserveValidator(){RuleFor(x=>x.ReserveDate).NotEmpty();RuleFor(x=>x.GoldValue).GreaterThanOrEqualTo(0);RuleFor(x=>x.CashInHand).GreaterThanOrEqualTo(0);RuleFor(x=>x.Deposits).GreaterThanOrEqualTo(0);RuleFor(x=>x).Must(x=>x.GoldValue+x.CashInHand+x.Deposits>0).WithMessage("At least one reserve value is required.");}}
public sealed class CreateObligationValidator:AbstractValidator<CreateObligationCommand>
{
    public CreateObligationValidator()
    {
        RuleFor(x=>x.ClientType).Must(ObligationClientTypes.IsValid).WithMessage("ClientType must be Bank, Company or Other.");
        RuleFor(x=>x.ClientName).NotEmpty().When(x=>x.ClientType==ObligationClientTypes.Other);
        RuleFor(x=>x.ClientName).MaximumLength(200);
        RuleFor(x=>x.BankId).NotEmpty().When(x=>x.ClientType==ObligationClientTypes.Bank).WithMessage("BankId is required when ClientType is Bank.");
        RuleFor(x=>x.CompanyId).NotEmpty().When(x=>x.ClientType==ObligationClientTypes.Company).WithMessage("CompanyId is required when ClientType is Company.");
        RuleFor(x=>x.CurrencyId).NotEmpty();
        RuleFor(x=>x.TotalAmount).GreaterThan(0);
        RuleFor(x=>x.DueDate).GreaterThanOrEqualTo(x=>x.ObligationDate).When(x=>x.DueDate.HasValue);
    }
}
