SET NOCOUNT ON;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetBeneficiaries @ActiveOnly bit=1 AS SELECT BeneficiaryId,BeneficiaryCode,BeneficiaryNameEn,BeneficiaryNameAr,IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.Transfers t WHERE t.BeneficiaryId=b.BeneficiaryId AND t.DeletedTime IS NULL) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.Beneficiaries b WHERE IsDeleted=0 AND(@ActiveOnly=0 OR IsActive=1) ORDER BY BeneficiaryNameEn;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetBeneficiaryById @BeneficiaryId uniqueidentifier AS SELECT BeneficiaryId,BeneficiaryCode,BeneficiaryNameEn,BeneficiaryNameAr,IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.Transfers t WHERE t.BeneficiaryId=b.BeneficiaryId AND t.DeletedTime IS NULL) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.Beneficiaries b WHERE BeneficiaryId=@BeneficiaryId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateBeneficiary @BeneficiaryCode nvarchar(50),@BeneficiaryNameEn nvarchar(200),@BeneficiaryNameAr nvarchar(200)=NULL,@CreatedBy nvarchar(100)=NULL AS BEGIN INSERT dbo.Beneficiaries(BeneficiaryCode,BeneficiaryNameEn,BeneficiaryNameAr,CreatedBy) OUTPUT inserted.BeneficiaryId VALUES(@BeneficiaryCode,@BeneficiaryNameEn,@BeneficiaryNameAr,@CreatedBy);END;
GO
CREATE OR ALTER PROCEDURE dbo.uspUpdateBeneficiary @BeneficiaryId uniqueidentifier,@BeneficiaryCode nvarchar(50),@BeneficiaryNameEn nvarchar(200),@BeneficiaryNameAr nvarchar(200)=NULL,@IsActive bit,@ModifiedBy nvarchar(100)=NULL AS UPDATE dbo.Beneficiaries SET BeneficiaryCode=@BeneficiaryCode,BeneficiaryNameEn=@BeneficiaryNameEn,BeneficiaryNameAr=@BeneficiaryNameAr,IsActive=@IsActive,ModifiedTime=SYSUTCDATETIME(),ModifiedBy=@ModifiedBy WHERE BeneficiaryId=@BeneficiaryId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteBeneficiary @BeneficiaryId uniqueidentifier,@DeletedBy nvarchar(100)=NULL AS BEGIN IF EXISTS(SELECT 1 FROM dbo.Transfers WHERE BeneficiaryId=@BeneficiaryId AND DeletedTime IS NULL) THROW 51001,'Beneficiary has movements.',1;UPDATE dbo.Beneficiaries SET IsDeleted=1,IsActive=0,DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE BeneficiaryId=@BeneficiaryId;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCurrencies @ActiveOnly bit=1 AS SELECT CurrencyId,CurrencyCode,CurrencyNameEn,CurrencyNameAr,Symbol,DecimalPlaces,IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.CorrespondentAccounts a WHERE a.CurrencyId=c.CurrencyId AND a.IsDeleted=0) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.Currencies c WHERE IsDeleted=0 AND(@ActiveOnly=0 OR IsActive=1) ORDER BY CurrencyCode;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCurrencyById @CurrencyId uniqueidentifier AS SELECT CurrencyId,CurrencyCode,CurrencyNameEn,CurrencyNameAr,Symbol,DecimalPlaces,IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.CorrespondentAccounts a WHERE a.CurrencyId=c.CurrencyId AND a.IsDeleted=0) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.Currencies c WHERE CurrencyId=@CurrencyId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateCurrency @CurrencyCode char(3),@CurrencyNameEn nvarchar(100),@CurrencyNameAr nvarchar(100)=NULL,@Symbol nvarchar(10)=NULL,@DecimalPlaces tinyint=2,@CreatedBy nvarchar(100)=NULL AS INSERT dbo.Currencies(CurrencyCode,CurrencyNameEn,CurrencyNameAr,Symbol,DecimalPlaces,CreatedBy) OUTPUT inserted.CurrencyId VALUES(UPPER(@CurrencyCode),@CurrencyNameEn,@CurrencyNameAr,@Symbol,@DecimalPlaces,@CreatedBy);
GO
CREATE OR ALTER PROCEDURE dbo.uspUpdateCurrency @CurrencyId uniqueidentifier,@CurrencyCode char(3),@CurrencyNameEn nvarchar(100),@CurrencyNameAr nvarchar(100)=NULL,@Symbol nvarchar(10)=NULL,@DecimalPlaces tinyint=2,@IsActive bit,@ModifiedBy nvarchar(100)=NULL AS UPDATE dbo.Currencies SET CurrencyCode=UPPER(@CurrencyCode),CurrencyNameEn=@CurrencyNameEn,CurrencyNameAr=@CurrencyNameAr,Symbol=@Symbol,DecimalPlaces=@DecimalPlaces,IsActive=@IsActive,ModifiedTime=SYSUTCDATETIME(),ModifiedBy=@ModifiedBy WHERE CurrencyId=@CurrencyId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteCurrency @CurrencyId uniqueidentifier,@DeletedBy nvarchar(100)=NULL AS BEGIN IF EXISTS(SELECT 1 FROM dbo.CorrespondentAccounts WHERE CurrencyId=@CurrencyId AND IsDeleted=0) THROW 51002,'Currency has accounts.',1;UPDATE dbo.Currencies SET IsDeleted=1,IsActive=0,DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE CurrencyId=@CurrencyId;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetResourceTypes @ActiveOnly bit=1 AS SELECT ResourceTypeId,ResourceTypeCode,ResourceTypeNameEn,ResourceTypeNameAr,IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.Resources r WHERE r.ResourceTypeId=t.ResourceTypeId AND r.DeletedTime IS NULL) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.ResourceTypes t WHERE IsDeleted=0 AND(@ActiveOnly=0 OR IsActive=1) ORDER BY ResourceTypeNameEn;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetResourceTypeById @ResourceTypeId uniqueidentifier AS SELECT ResourceTypeId,ResourceTypeCode,ResourceTypeNameEn,ResourceTypeNameAr,IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.Resources r WHERE r.ResourceTypeId=t.ResourceTypeId AND r.DeletedTime IS NULL) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.ResourceTypes t WHERE ResourceTypeId=@ResourceTypeId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateResourceType @ResourceTypeCode nvarchar(50),@ResourceTypeNameEn nvarchar(100),@ResourceTypeNameAr nvarchar(100)=NULL,@CreatedBy nvarchar(100)=NULL AS INSERT dbo.ResourceTypes(ResourceTypeCode,ResourceTypeNameEn,ResourceTypeNameAr,CreatedBy) OUTPUT inserted.ResourceTypeId VALUES(@ResourceTypeCode,@ResourceTypeNameEn,@ResourceTypeNameAr,@CreatedBy);
GO
CREATE OR ALTER PROCEDURE dbo.uspUpdateResourceType @ResourceTypeId uniqueidentifier,@ResourceTypeCode nvarchar(50),@ResourceTypeNameEn nvarchar(100),@ResourceTypeNameAr nvarchar(100)=NULL,@IsActive bit,@ModifiedBy nvarchar(100)=NULL AS UPDATE dbo.ResourceTypes SET ResourceTypeCode=@ResourceTypeCode,ResourceTypeNameEn=@ResourceTypeNameEn,ResourceTypeNameAr=@ResourceTypeNameAr,IsActive=@IsActive,ModifiedTime=SYSUTCDATETIME(),ModifiedBy=@ModifiedBy WHERE ResourceTypeId=@ResourceTypeId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteResourceType @ResourceTypeId uniqueidentifier,@DeletedBy nvarchar(100)=NULL AS BEGIN IF EXISTS(SELECT 1 FROM dbo.Resources WHERE ResourceTypeId=@ResourceTypeId AND DeletedTime IS NULL) THROW 51003,'Resource type has movements.',1;UPDATE dbo.ResourceTypes SET IsDeleted=1,IsActive=0,DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE ResourceTypeId=@ResourceTypeId;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCorrespondents @ActiveOnly bit=1 AS SELECT c.CorrespondentId,c.CorrespondentCode,c.CorrespondentNameEn,c.CorrespondentNameAr,c.CountryId,k.CountryNameEn,k.CountryNameAr,c.IsActive FROM dbo.Correspondents c LEFT JOIN dbo.Countries k ON k.CountryId=c.CountryId WHERE c.IsDeleted=0 AND(@ActiveOnly=0 OR c.IsActive=1) ORDER BY c.CorrespondentNameEn;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCorrespondentById @CorrespondentId uniqueidentifier AS SELECT c.CorrespondentId,c.CorrespondentCode,c.CorrespondentNameEn,c.CorrespondentNameAr,c.CountryId,k.CountryNameEn,k.CountryNameAr,c.IsActive FROM dbo.Correspondents c LEFT JOIN dbo.Countries k ON k.CountryId=c.CountryId WHERE c.CorrespondentId=@CorrespondentId AND c.IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateCorrespondent @CorrespondentCode nvarchar(50),@CorrespondentNameEn nvarchar(200),@CorrespondentNameAr nvarchar(200)=NULL,@CountryId uniqueidentifier=NULL,@CreatedBy nvarchar(100)=NULL,@CorrespondentId uniqueidentifier OUTPUT AS BEGIN SET @CorrespondentId=NEWID();INSERT dbo.Correspondents(CorrespondentId,CorrespondentCode,CorrespondentNameEn,CorrespondentNameAr,CountryId,CreatedBy)VALUES(@CorrespondentId,@CorrespondentCode,@CorrespondentNameEn,@CorrespondentNameAr,@CountryId,@CreatedBy);END;
GO
CREATE OR ALTER PROCEDURE dbo.uspUpdateCorrespondent @CorrespondentId uniqueidentifier,@CorrespondentCode nvarchar(50),@CorrespondentNameEn nvarchar(200),@CorrespondentNameAr nvarchar(200)=NULL,@CountryId uniqueidentifier=NULL,@IsActive bit,@ModifiedBy nvarchar(100)=NULL AS UPDATE dbo.Correspondents SET CorrespondentCode=@CorrespondentCode,CorrespondentNameEn=@CorrespondentNameEn,CorrespondentNameAr=@CorrespondentNameAr,CountryId=@CountryId,IsActive=@IsActive,ModifiedTime=SYSUTCDATETIME(),ModifiedBy=@ModifiedBy WHERE CorrespondentId=@CorrespondentId AND IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteCorrespondent @CorrespondentId uniqueidentifier,@DeletedBy nvarchar(100)=NULL AS BEGIN IF EXISTS(SELECT 1 FROM dbo.CorrespondentAccounts WHERE CorrespondentId=@CorrespondentId AND IsDeleted=0) THROW 51004,'Correspondent has accounts.',1;UPDATE dbo.Correspondents SET IsDeleted=1,IsActive=0,DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE CorrespondentId=@CorrespondentId;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCorrespondentAccounts @CorrespondentId uniqueidentifier=NULL,@CurrencyId uniqueidentifier=NULL,@ActiveOnly bit=1 AS SELECT a.CorrespondentAccountId,a.CorrespondentId,c.CorrespondentNameEn,c.CorrespondentNameAr,a.CurrencyId,u.CurrencyCode,a.AccountNumber,a.OpeningBalance,a.CurrentBalance,a.IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.Resources r WHERE r.CorrespondentAccountId=a.CorrespondentAccountId AND r.DeletedTime IS NULL) OR EXISTS(SELECT 1 FROM dbo.Transfers t WHERE t.CorrespondentAccountId=a.CorrespondentAccountId AND t.DeletedTime IS NULL) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.CorrespondentAccounts a JOIN dbo.Correspondents c ON c.CorrespondentId=a.CorrespondentId JOIN dbo.Currencies u ON u.CurrencyId=a.CurrencyId WHERE a.IsDeleted=0 AND(@CorrespondentId IS NULL OR a.CorrespondentId=@CorrespondentId)AND(@CurrencyId IS NULL OR a.CurrencyId=@CurrencyId)AND(@ActiveOnly=0 OR a.IsActive=1) ORDER BY c.CorrespondentNameEn,u.CurrencyCode;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCorrespondentAccountById @CorrespondentAccountId uniqueidentifier AS SELECT a.CorrespondentAccountId,a.CorrespondentId,c.CorrespondentNameEn,c.CorrespondentNameAr,a.CurrencyId,u.CurrencyCode,a.AccountNumber,a.OpeningBalance,a.CurrentBalance,a.IsActive,CAST(CASE WHEN EXISTS(SELECT 1 FROM dbo.Resources r WHERE r.CorrespondentAccountId=a.CorrespondentAccountId AND r.DeletedTime IS NULL) OR EXISTS(SELECT 1 FROM dbo.Transfers t WHERE t.CorrespondentAccountId=a.CorrespondentAccountId AND t.DeletedTime IS NULL) THEN 1 ELSE 0 END AS bit) HasMovements FROM dbo.CorrespondentAccounts a JOIN dbo.Correspondents c ON c.CorrespondentId=a.CorrespondentId JOIN dbo.Currencies u ON u.CurrencyId=a.CurrencyId WHERE a.CorrespondentAccountId=@CorrespondentAccountId AND a.IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateCorrespondentAccount @CorrespondentId uniqueidentifier,@CurrencyId uniqueidentifier,@AccountNumber nvarchar(100),@OpeningBalance decimal(19,4),@CreatedBy nvarchar(100)=NULL,@CorrespondentAccountId uniqueidentifier OUTPUT AS BEGIN SET @CorrespondentAccountId=NEWID();INSERT dbo.CorrespondentAccounts(CorrespondentAccountId,CorrespondentId,CurrencyId,AccountNumber,OpeningBalance,CurrentBalance,CreatedBy)VALUES(@CorrespondentAccountId,@CorrespondentId,@CurrencyId,@AccountNumber,@OpeningBalance,@OpeningBalance,@CreatedBy);END;
GO
CREATE OR ALTER PROCEDURE dbo.uspUpdateCorrespondentAccount @CorrespondentAccountId uniqueidentifier,@CorrespondentId uniqueidentifier,@CurrencyId uniqueidentifier,@AccountNumber nvarchar(100),@OpeningBalance decimal(19,4),@IsActive bit,@ModifiedBy nvarchar(100)=NULL AS BEGIN IF EXISTS(SELECT 1 FROM dbo.Resources WHERE CorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL) AND EXISTS(SELECT 1 FROM dbo.CorrespondentAccounts WHERE CorrespondentAccountId=@CorrespondentAccountId AND CurrencyId<>@CurrencyId) THROW 51005,'Cannot change currency after movements.',1;UPDATE dbo.CorrespondentAccounts SET CorrespondentId=@CorrespondentId,CurrencyId=@CurrencyId,AccountNumber=@AccountNumber,CurrentBalance=CurrentBalance+(@OpeningBalance-OpeningBalance),OpeningBalance=@OpeningBalance,IsActive=@IsActive,ModifiedTime=SYSUTCDATETIME(),ModifiedBy=@ModifiedBy WHERE CorrespondentAccountId=@CorrespondentAccountId AND IsDeleted=0;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteCorrespondentAccount @CorrespondentAccountId uniqueidentifier,@DeletedBy nvarchar(100)=NULL AS BEGIN IF EXISTS(SELECT 1 FROM dbo.Resources WHERE CorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL) OR EXISTS(SELECT 1 FROM dbo.Transfers WHERE CorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL) OR EXISTS(SELECT 1 FROM dbo.Coverages WHERE(FromCorrespondentAccountId=@CorrespondentAccountId OR ToCorrespondentAccountId=@CorrespondentAccountId)AND DeletedTime IS NULL) OR EXISTS(SELECT 1 FROM dbo.Deals WHERE(FromCorrespondentAccountId=@CorrespondentAccountId OR ToCorrespondentAccountId=@CorrespondentAccountId)AND DeletedTime IS NULL) THROW 51006,'Account has movements.',1;UPDATE dbo.CorrespondentAccounts SET IsDeleted=1,IsActive=0,DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE CorrespondentAccountId=@CorrespondentAccountId;END;
