SET NOCOUNT ON;
GO
CREATE OR ALTER PROCEDURE dbo.uspAddResourceToCorrespondentAccount @ResourceDate date,@CorrespondentAccountId uniqueidentifier,@Amount decimal(19,4),@ResourceTypeId uniqueidentifier,@Notes nvarchar(300)=NULL,@CreatedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;UPDATE dbo.CorrespondentAccounts WITH(UPDLOCK) SET CurrentBalance=CurrentBalance+@Amount WHERE CorrespondentAccountId=@CorrespondentAccountId AND IsActive=1 AND IsDeleted=0;IF @@ROWCOUNT=0 THROW 52001,'Account not found or inactive.',1;INSERT dbo.Resources(ResourceDate,CorrespondentAccountId,Amount,ResourceTypeId,Notes,CreatedBy)VALUES(@ResourceDate,@CorrespondentAccountId,@Amount,@ResourceTypeId,@Notes,@CreatedBy);COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteResource @ResourceId uniqueidentifier,@DeletedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @a uniqueidentifier,@v decimal(19,4);SELECT @a=CorrespondentAccountId,@v=Amount FROM dbo.Resources WITH(UPDLOCK) WHERE ResourceId=@ResourceId AND DeletedTime IS NULL;IF @a IS NULL THROW 52002,'Resource not found.',1;IF(SELECT CurrentBalance FROM dbo.CorrespondentAccounts WITH(UPDLOCK) WHERE CorrespondentAccountId=@a)<@v THROW 52003,'Insufficient balance to reverse resource.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance-@v WHERE CorrespondentAccountId=@a;UPDATE dbo.Resources SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE ResourceId=@ResourceId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetResourceStatement @CorrespondentAccountId uniqueidentifier,@StartDate date=NULL,@EndDate date=NULL AS SELECT r.ResourceId,r.ResourceDate,t.ResourceTypeNameEn ResourceType,r.Amount,CAST(NULL AS nvarchar(100))ReferenceNo,r.Notes FROM dbo.Resources r JOIN dbo.ResourceTypes t ON t.ResourceTypeId=r.ResourceTypeId WHERE r.CorrespondentAccountId=@CorrespondentAccountId AND r.DeletedTime IS NULL AND(@StartDate IS NULL OR r.ResourceDate>=@StartDate)AND(@EndDate IS NULL OR r.ResourceDate<=@EndDate)ORDER BY r.ResourceDate,r.CreatedTime;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateTransfer @TransferDate datetime2,@BeneficiaryId uniqueidentifier,@CorrespondentAccountId uniqueidentifier,@Amount decimal(19,4),@Purpose nvarchar(500),@ReferenceNo nvarchar(100),@OperationTypeId uniqueidentifier=NULL,@ResourceTypeId uniqueidentifier=NULL,@UsageTypeId uniqueidentifier=NULL,@BankId uniqueidentifier=NULL,@CreatedBy nvarchar(100),@TransferId uniqueidentifier OUTPUT AS BEGIN SET @TransferId=NEWID();IF @OperationTypeId IS NULL SELECT TOP(1)@OperationTypeId=OperationTypeId FROM dbo.OperationTypes WHERE OperationTypeCode='TRANSFER';IF @UsageTypeId IS NULL SELECT TOP(1)@UsageTypeId=UsageTypeId FROM dbo.UsageTypes WHERE UsageTypeCode='BENEFICIARY';IF @ResourceTypeId IS NULL SELECT TOP(1)@ResourceTypeId=ResourceTypeId FROM dbo.ResourceTypes WHERE IsActive=1 AND IsDeleted=0 ORDER BY ResourceTypeCode;IF @BankId IS NULL SELECT TOP(1)@BankId=BankId FROM dbo.Banks WHERE IsActive=1 AND IsDeleted=0 ORDER BY BankCode;INSERT dbo.Transfers(TransferId,TransferDate,BeneficiaryId,CorrespondentAccountId,Amount,Purpose,ReferenceNo,OperationTypeId,ResourceTypeId,UsageTypeId,BankId,CreatedBy)VALUES(@TransferId,@TransferDate,@BeneficiaryId,@CorrespondentAccountId,@Amount,@Purpose,@ReferenceNo,@OperationTypeId,@ResourceTypeId,@UsageTypeId,@BankId,@CreatedBy);END;
GO
CREATE OR ALTER PROCEDURE dbo.uspConfirmTransfer @TransferId uniqueidentifier,@ConfirmedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @a uniqueidentifier,@v decimal(19,4),@s nvarchar(20);SELECT @a=CorrespondentAccountId,@v=Amount,@s=TransferStatus FROM dbo.Transfers WITH(UPDLOCK) WHERE TransferId=@TransferId AND DeletedTime IS NULL;IF @s<>'Pending' THROW 52010,'Only pending transfers can be confirmed.',1;UPDATE dbo.CorrespondentAccounts WITH(UPDLOCK) SET CurrentBalance=CurrentBalance-@v WHERE CorrespondentAccountId=@a AND CurrentBalance>=@v AND IsActive=1 AND IsDeleted=0;IF @@ROWCOUNT=0 THROW 52011,'Insufficient account balance.',1;UPDATE dbo.Transfers SET TransferStatus='Confirmed',ConfirmedTime=SYSUTCDATETIME(),ConfirmedBy=@ConfirmedBy WHERE TransferId=@TransferId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspRejectTransfer @TransferId uniqueidentifier,@RejectedBy nvarchar(100),@RejectReason nvarchar(500)=NULL AS UPDATE dbo.Transfers SET TransferStatus='Rejected',RejectedTime=SYSUTCDATETIME(),RejectedBy=@RejectedBy,RejectReason=@RejectReason WHERE TransferId=@TransferId AND TransferStatus='Pending' AND DeletedTime IS NULL;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteTransfer @TransferId uniqueidentifier,@DeletedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @a uniqueidentifier,@v decimal(19,4),@s nvarchar(20);SELECT @a=CorrespondentAccountId,@v=Amount,@s=TransferStatus FROM dbo.Transfers WITH(UPDLOCK) WHERE TransferId=@TransferId AND DeletedTime IS NULL;IF @a IS NULL THROW 52012,'Transfer not found.',1;IF @s='Confirmed' UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance+@v WHERE CorrespondentAccountId=@a;UPDATE dbo.Transfers SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE TransferId=@TransferId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetBeneficiaryStatement @BeneficiaryId uniqueidentifier,@StartDate date=NULL,@EndDate date=NULL AS SELECT t.TransferId,t.TransferDate,a.AccountNumber,c.CorrespondentNameEn AccountName,t.Amount,t.TransferStatus,t.ReferenceNo,t.Purpose,t.ConfirmedTime,t.RejectedTime,t.RejectReason FROM dbo.Transfers t JOIN dbo.CorrespondentAccounts a ON a.CorrespondentAccountId=t.CorrespondentAccountId JOIN dbo.Correspondents c ON c.CorrespondentId=a.CorrespondentId WHERE t.BeneficiaryId=@BeneficiaryId AND t.DeletedTime IS NULL AND(@StartDate IS NULL OR t.TransferDate>=@StartDate)AND(@EndDate IS NULL OR t.TransferDate<DATEADD(day,1,@EndDate))ORDER BY t.TransferDate;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateCoverage @FromCorrespondentAccountId uniqueidentifier,@ToCorrespondentAccountId uniqueidentifier,@Amount decimal(19,4),@ReferenceNo nvarchar(100)=NULL,@Narration nvarchar(500)=NULL,@TransactionDate datetime2,@CreatedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @fc uniqueidentifier,@tc uniqueidentifier;SELECT @fc=CurrencyId FROM dbo.CorrespondentAccounts WITH(UPDLOCK) WHERE CorrespondentAccountId=@FromCorrespondentAccountId AND IsActive=1 AND IsDeleted=0;SELECT @tc=CurrencyId FROM dbo.CorrespondentAccounts WITH(UPDLOCK) WHERE CorrespondentAccountId=@ToCorrespondentAccountId AND IsActive=1 AND IsDeleted=0;IF @fc IS NULL OR @tc IS NULL OR @fc<>@tc OR @FromCorrespondentAccountId=@ToCorrespondentAccountId THROW 52020,'Coverage requires distinct active accounts in the same currency.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance-@Amount WHERE CorrespondentAccountId=@FromCorrespondentAccountId AND CurrentBalance>=@Amount;IF @@ROWCOUNT=0 THROW 52021,'Insufficient source balance.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance+@Amount WHERE CorrespondentAccountId=@ToCorrespondentAccountId;DECLARE @id uniqueidentifier=NEWID();INSERT dbo.Coverages(CoverageId,FromCorrespondentAccountId,ToCorrespondentAccountId,Amount,ReferenceNo,Narration,TransactionDate,CreatedBy)VALUES(@id,@FromCorrespondentAccountId,@ToCorrespondentAccountId,@Amount,@ReferenceNo,@Narration,@TransactionDate,@CreatedBy);COMMIT;SELECT @id;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteCoverage @CoverageId uniqueidentifier,@DeletedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @f uniqueidentifier,@t uniqueidentifier,@v decimal(19,4);SELECT @f=FromCorrespondentAccountId,@t=ToCorrespondentAccountId,@v=Amount FROM dbo.Coverages WITH(UPDLOCK) WHERE CoverageId=@CoverageId AND DeletedTime IS NULL;IF @f IS NULL THROW 52022,'Coverage not found.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance-@v WHERE CorrespondentAccountId=@t AND CurrentBalance>=@v;IF @@ROWCOUNT=0 THROW 52023,'Destination balance is insufficient to reverse coverage.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance+@v WHERE CorrespondentAccountId=@f;UPDATE dbo.Coverages SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE CoverageId=@CoverageId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCoverages @CorrespondentAccountId uniqueidentifier=NULL,@StartDate datetime2=NULL,@EndDate datetime2=NULL AS SELECT x.CoverageId,x.FromCorrespondentAccountId,fc.CorrespondentNameEn FromCorrespondentName,x.ToCorrespondentAccountId,tc.CorrespondentNameEn ToCorrespondentName,fa.CurrencyId,u.CurrencyCode,x.Amount,x.ReferenceNo,x.Narration,x.TransactionDate FROM dbo.Coverages x JOIN dbo.CorrespondentAccounts fa ON fa.CorrespondentAccountId=x.FromCorrespondentAccountId JOIN dbo.Correspondents fc ON fc.CorrespondentId=fa.CorrespondentId JOIN dbo.CorrespondentAccounts ta ON ta.CorrespondentAccountId=x.ToCorrespondentAccountId JOIN dbo.Correspondents tc ON tc.CorrespondentId=ta.CorrespondentId JOIN dbo.Currencies u ON u.CurrencyId=fa.CurrencyId WHERE x.DeletedTime IS NULL AND(@CorrespondentAccountId IS NULL OR x.FromCorrespondentAccountId=@CorrespondentAccountId OR x.ToCorrespondentAccountId=@CorrespondentAccountId)AND(@StartDate IS NULL OR x.TransactionDate>=@StartDate)AND(@EndDate IS NULL OR x.TransactionDate<DATEADD(day,1,CONVERT(date,@EndDate)))ORDER BY x.TransactionDate DESC;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateDeal @FromCorrespondentAccountId uniqueidentifier,@ToCorrespondentAccountId uniqueidentifier,@FromAmount decimal(19,4),@ExchangeRate decimal(19,8),@ReferenceNo nvarchar(100)=NULL,@Narration nvarchar(500)=NULL,@TransactionDate datetime2,@CreatedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @fc uniqueidentifier,@tc uniqueidentifier,@to decimal(19,4)=ROUND(@FromAmount*@ExchangeRate,4);SELECT @fc=CurrencyId FROM dbo.CorrespondentAccounts WITH(UPDLOCK) WHERE CorrespondentAccountId=@FromCorrespondentAccountId AND IsActive=1 AND IsDeleted=0;SELECT @tc=CurrencyId FROM dbo.CorrespondentAccounts WITH(UPDLOCK) WHERE CorrespondentAccountId=@ToCorrespondentAccountId AND IsActive=1 AND IsDeleted=0;IF @fc IS NULL OR @tc IS NULL OR @fc=@tc THROW 52030,'Deal requires active accounts in different currencies.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance-@FromAmount WHERE CorrespondentAccountId=@FromCorrespondentAccountId AND CurrentBalance>=@FromAmount;IF @@ROWCOUNT=0 THROW 52031,'Insufficient source balance.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance+@to WHERE CorrespondentAccountId=@ToCorrespondentAccountId;DECLARE @id uniqueidentifier=NEWID();INSERT dbo.Deals(DealId,FromCorrespondentAccountId,ToCorrespondentAccountId,FromAmount,ExchangeRate,ReferenceNo,Narration,TransactionDate,CreatedBy)VALUES(@id,@FromCorrespondentAccountId,@ToCorrespondentAccountId,@FromAmount,@ExchangeRate,@ReferenceNo,@Narration,@TransactionDate,@CreatedBy);COMMIT;SELECT @id;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteDeal @DealId uniqueidentifier,@DeletedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @f uniqueidentifier,@t uniqueidentifier,@fv decimal(19,4),@tv decimal(19,4);SELECT @f=FromCorrespondentAccountId,@t=ToCorrespondentAccountId,@fv=FromAmount,@tv=ToAmount FROM dbo.Deals WITH(UPDLOCK) WHERE DealId=@DealId AND DeletedTime IS NULL;IF @f IS NULL THROW 52032,'Deal not found.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance-@tv WHERE CorrespondentAccountId=@t AND CurrentBalance>=@tv;IF @@ROWCOUNT=0 THROW 52033,'Destination balance is insufficient to reverse deal.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance+@fv WHERE CorrespondentAccountId=@f;UPDATE dbo.Deals SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE DealId=@DealId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetDeals @CorrespondentAccountId uniqueidentifier=NULL,@StartDate datetime2=NULL,@EndDate datetime2=NULL AS SELECT d.DealId,d.FromCorrespondentAccountId,fc.CorrespondentNameEn FromCorrespondentName,fu.CurrencyCode FromCurrencyCode,d.ToCorrespondentAccountId,tc.CorrespondentNameEn ToCorrespondentName,tu.CurrencyCode ToCurrencyCode,d.FromAmount,d.ExchangeRate,d.ToAmount,d.ReferenceNo,d.Narration,d.TransactionDate FROM dbo.Deals d JOIN dbo.CorrespondentAccounts fa ON fa.CorrespondentAccountId=d.FromCorrespondentAccountId JOIN dbo.Correspondents fc ON fc.CorrespondentId=fa.CorrespondentId JOIN dbo.Currencies fu ON fu.CurrencyId=fa.CurrencyId JOIN dbo.CorrespondentAccounts ta ON ta.CorrespondentAccountId=d.ToCorrespondentAccountId JOIN dbo.Correspondents tc ON tc.CorrespondentId=ta.CorrespondentId JOIN dbo.Currencies tu ON tu.CurrencyId=ta.CurrencyId WHERE d.DeletedTime IS NULL AND(@CorrespondentAccountId IS NULL OR d.FromCorrespondentAccountId=@CorrespondentAccountId OR d.ToCorrespondentAccountId=@CorrespondentAccountId)AND(@StartDate IS NULL OR d.TransactionDate>=@StartDate)AND(@EndDate IS NULL OR d.TransactionDate<DATEADD(day,1,CONVERT(date,@EndDate)))ORDER BY d.TransactionDate DESC;
