SET NOCOUNT ON;
GO
CREATE OR ALTER PROCEDURE dbo.uspAddExchangeRate @RateDate date,@FromCurrencyId uniqueidentifier,@ToCurrencyId uniqueidentifier,@RateValue decimal(19,8),@CreatedBy nvarchar(100) AS INSERT dbo.ExchangeRates(RateDate,FromCurrencyId,ToCurrencyId,RateValue,CreatedBy)VALUES(@RateDate,@FromCurrencyId,@ToCurrencyId,@RateValue,@CreatedBy);
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteExchangeRate @ExchangeRateId uniqueidentifier,@DeletedBy nvarchar(100) AS UPDATE dbo.ExchangeRates SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE ExchangeRateId=@ExchangeRateId AND DeletedTime IS NULL;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetExchangeRate @RateDate date=NULL,@FromCurrencyId uniqueidentifier=NULL,@ToCurrencyId uniqueidentifier=NULL AS SELECT r.ExchangeRateId,r.RateDate,r.FromCurrencyId,f.CurrencyCode FromCurrencyCode,f.CurrencyNameAr FromCurrencyNameAr,f.CurrencyNameEn FromCurrencyNameEn,r.ToCurrencyId,t.CurrencyCode ToCurrencyCode,t.CurrencyNameAr ToCurrencyNameAr,t.CurrencyNameEn ToCurrencyNameEn,r.RateValue FROM dbo.ExchangeRates r JOIN dbo.Currencies f ON f.CurrencyId=r.FromCurrencyId JOIN dbo.Currencies t ON t.CurrencyId=r.ToCurrencyId WHERE r.DeletedTime IS NULL AND(@RateDate IS NULL OR r.RateDate=@RateDate)AND(@FromCurrencyId IS NULL OR r.FromCurrencyId=@FromCurrencyId)AND(@ToCurrencyId IS NULL OR r.ToCurrencyId=@ToCurrencyId)ORDER BY r.RateDate DESC;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateReserveSnapshot @ReserveDate date,@GoldValue decimal(19,4),@CashInHand decimal(19,4),@Deposits decimal(19,4),@Notes nvarchar(500)=NULL,@CreatedBy nvarchar(100) AS INSERT dbo.ReserveSnapshots(ReserveDate,GoldValue,CashInHand,Deposits,Notes,CreatedBy)OUTPUT inserted.ReserveSnapshotId VALUES(@ReserveDate,@GoldValue,@CashInHand,@Deposits,@Notes,@CreatedBy);
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteReserveSnapshot @ReserveSnapshotId uniqueidentifier,@DeletedBy nvarchar(100) AS UPDATE dbo.ReserveSnapshots SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE ReserveSnapshotId=@ReserveSnapshotId AND DeletedTime IS NULL;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetReserveSnapshots @StartDate date=NULL,@EndDate date=NULL AS SELECT ReserveSnapshotId,ReserveDate,GoldValue,CashInHand,Deposits,GoldValue+CashInHand+Deposits TotalValue,Notes FROM dbo.ReserveSnapshots WHERE DeletedTime IS NULL AND(@StartDate IS NULL OR ReserveDate>=@StartDate)AND(@EndDate IS NULL OR ReserveDate<=@EndDate)ORDER BY ReserveDate DESC,CreatedTime DESC;
GO
CREATE OR ALTER PROCEDURE dbo.uspCreateObligation @ObligationDate date,@ClientName nvarchar(200),@CurrencyId uniqueidentifier,@TotalAmount decimal(19,4),@DueDate date=NULL,@ReferenceNo nvarchar(100)=NULL,@Notes nvarchar(500)=NULL,@CreatedBy nvarchar(100) AS INSERT dbo.Obligations(ObligationDate,ClientName,CurrencyId,TotalAmount,DueDate,ReferenceNo,Notes,CreatedBy)OUTPUT inserted.ObligationId VALUES(@ObligationDate,@ClientName,@CurrencyId,@TotalAmount,@DueDate,@ReferenceNo,@Notes,@CreatedBy);
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteObligation @ObligationId uniqueidentifier,@DeletedBy nvarchar(100) AS BEGIN IF EXISTS(SELECT 1 FROM dbo.ObligationPayments WHERE ObligationId=@ObligationId AND DeletedTime IS NULL) THROW 53001,'Obligation has payments.',1;UPDATE dbo.Obligations SET IsActive=0,DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE ObligationId=@ObligationId;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetObligations @ActiveOnly bit=1 AS SELECT o.ObligationId,o.ObligationDate,o.ClientName,o.CurrencyId,c.CurrencyNameAr,c.CurrencyNameEn,o.TotalAmount,o.PaidAmount,o.TotalAmount-o.PaidAmount RemainingAmount,o.DueDate,o.ReferenceNo,o.Notes,o.IsActive FROM dbo.Obligations o JOIN dbo.Currencies c ON c.CurrencyId=o.CurrencyId WHERE o.DeletedTime IS NULL AND(@ActiveOnly=0 OR o.IsActive=1)ORDER BY o.ObligationDate DESC;
GO
CREATE OR ALTER PROCEDURE dbo.uspAddObligationPayment @ObligationId uniqueidentifier,@CorrespondentAccountId uniqueidentifier,@PaymentDate date,@Amount decimal(19,4),@ReferenceNo nvarchar(100)=NULL,@Notes nvarchar(500)=NULL,@CreatedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @oc uniqueidentifier,@ac uniqueidentifier,@remaining decimal(19,4);SELECT @oc=CurrencyId,@remaining=TotalAmount-PaidAmount FROM dbo.Obligations WITH(UPDLOCK) WHERE ObligationId=@ObligationId AND IsActive=1 AND DeletedTime IS NULL;SELECT @ac=CurrencyId FROM dbo.CorrespondentAccounts WITH(UPDLOCK) WHERE CorrespondentAccountId=@CorrespondentAccountId AND IsActive=1 AND IsDeleted=0;IF @oc IS NULL THROW 53002,'Obligation not found.',1;IF @oc<>@ac THROW 53003,'Payment account currency mismatch.',1;IF @Amount>@remaining THROW 53004,'Payment exceeds remaining obligation.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance-@Amount WHERE CorrespondentAccountId=@CorrespondentAccountId AND CurrentBalance>=@Amount;IF @@ROWCOUNT=0 THROW 53005,'Insufficient account balance.',1;INSERT dbo.ObligationPayments(ObligationId,CorrespondentAccountId,PaymentDate,Amount,ReferenceNo,Notes,CreatedBy)VALUES(@ObligationId,@CorrespondentAccountId,@PaymentDate,@Amount,@ReferenceNo,@Notes,@CreatedBy);UPDATE dbo.Obligations SET PaidAmount=PaidAmount+@Amount,IsActive=CASE WHEN PaidAmount+@Amount>=TotalAmount THEN 0 ELSE 1 END WHERE ObligationId=@ObligationId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspDeleteObligationPayment @ObligationPaymentId uniqueidentifier,@DeletedBy nvarchar(100) AS BEGIN SET XACT_ABORT ON;BEGIN TRAN;DECLARE @o uniqueidentifier,@a uniqueidentifier,@v decimal(19,4);SELECT @o=ObligationId,@a=CorrespondentAccountId,@v=Amount FROM dbo.ObligationPayments WITH(UPDLOCK) WHERE ObligationPaymentId=@ObligationPaymentId AND DeletedTime IS NULL;IF @o IS NULL THROW 53006,'Payment not found.',1;UPDATE dbo.CorrespondentAccounts SET CurrentBalance=CurrentBalance+@v WHERE CorrespondentAccountId=@a;UPDATE dbo.Obligations SET PaidAmount=PaidAmount-@v,IsActive=1 WHERE ObligationId=@o;UPDATE dbo.ObligationPayments SET DeletedTime=SYSUTCDATETIME(),DeletedBy=@DeletedBy WHERE ObligationPaymentId=@ObligationPaymentId;COMMIT;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetObligationStatement @ObligationId uniqueidentifier AS BEGIN SELECT o.ObligationId,o.ObligationDate,o.ClientName,o.CurrencyId,c.CurrencyNameAr,c.CurrencyNameEn,o.TotalAmount,o.PaidAmount,o.TotalAmount-o.PaidAmount RemainingAmount,o.DueDate,o.ReferenceNo,o.Notes,o.IsActive FROM dbo.Obligations o JOIN dbo.Currencies c ON c.CurrencyId=o.CurrencyId WHERE o.ObligationId=@ObligationId AND o.DeletedTime IS NULL;SELECT ObligationPaymentId,ObligationId,PaymentDate,Amount,ReferenceNo,Notes,CreatedBy,CreatedTime FROM dbo.ObligationPayments WHERE ObligationId=@ObligationId AND DeletedTime IS NULL ORDER BY PaymentDate;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCurrencyBalances AS SELECT c.CurrencyId,c.CurrencyCode,c.CurrencyNameAr,c.CurrencyNameEn,COALESCE(SUM(a.OpeningBalance),0)TotalOpeningBalance,COALESCE((SELECT SUM(r.Amount) FROM dbo.Resources r JOIN dbo.CorrespondentAccounts ra ON ra.CorrespondentAccountId=r.CorrespondentAccountId WHERE ra.CurrencyId=c.CurrencyId AND r.DeletedTime IS NULL),0)TotalResources,COALESCE((SELECT SUM(x.Amount) FROM dbo.Coverages x JOIN dbo.CorrespondentAccounts xa ON xa.CorrespondentAccountId=x.FromCorrespondentAccountId WHERE xa.CurrencyId=c.CurrencyId AND x.DeletedTime IS NULL),0)TotalCoverageOut,COALESCE((SELECT SUM(x.Amount) FROM dbo.Coverages x JOIN dbo.CorrespondentAccounts xa ON xa.CorrespondentAccountId=x.ToCorrespondentAccountId WHERE xa.CurrencyId=c.CurrencyId AND x.DeletedTime IS NULL),0)TotalCoverageIn,COALESCE((SELECT SUM(t.Amount) FROM dbo.Transfers t JOIN dbo.CorrespondentAccounts ta ON ta.CorrespondentAccountId=t.CorrespondentAccountId WHERE ta.CurrencyId=c.CurrencyId AND t.TransferStatus='Confirmed' AND t.DeletedTime IS NULL),0)TotalConfirmedTransfers,COALESCE(SUM(a.CurrentBalance),0)CurrentBalance FROM dbo.Currencies c LEFT JOIN dbo.CorrespondentAccounts a ON a.CurrencyId=c.CurrencyId AND a.IsDeleted=0 WHERE c.IsDeleted=0 GROUP BY c.CurrencyId,c.CurrencyCode,c.CurrencyNameAr,c.CurrencyNameEn;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCorrespondentBalancesByCurrency AS SELECT c.CurrencyId,c.CurrencyNameAr,c.CurrencyNameEn,c.Symbol,COALESCE(SUM(a.CurrentBalance),0)TotalBalance FROM dbo.Currencies c LEFT JOIN dbo.CorrespondentAccounts a ON a.CurrencyId=c.CurrencyId AND a.IsDeleted=0 WHERE c.IsDeleted=0 GROUP BY c.CurrencyId,c.CurrencyNameAr,c.CurrencyNameEn,c.Symbol;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetDailyValuation @ValuationDate date=NULL AS SELECT r.ReserveSnapshotId DailyValuationId,r.ReserveDate ValuationDate,r.CashInHand CashInHandUsd,CAST(0 AS decimal(19,4))GoldOunces,CAST(0 AS decimal(19,4))GoldPricePerOunceUsd,r.GoldValue GoldValueUsd,r.Notes FROM dbo.ReserveSnapshots r WHERE r.DeletedTime IS NULL AND(@ValuationDate IS NULL OR r.ReserveDate=@ValuationDate)ORDER BY r.ReserveDate;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCorrespondentAccountStatement @CorrespondentAccountId uniqueidentifier,@StartDate datetime2=NULL,@EndDate datetime2=NULL AS BEGIN DECLARE @opening decimal(19,4)=(SELECT OpeningBalance FROM dbo.CorrespondentAccounts WHERE CorrespondentAccountId=@CorrespondentAccountId);WITH e AS(SELECT CAST(ResourceDate AS datetime2)EventDate,'Resource'EventType,Amount AmountIn,CAST(0 AS decimal(19,4))AmountOut,Notes FROM dbo.Resources WHERE CorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL UNION ALL SELECT TransferDate,'Transfer',0,Amount,Purpose FROM dbo.Transfers WHERE CorrespondentAccountId=@CorrespondentAccountId AND TransferStatus='Confirmed' AND DeletedTime IS NULL UNION ALL SELECT TransactionDate,'Coverage in',Amount,0,Narration FROM dbo.Coverages WHERE ToCorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL UNION ALL SELECT TransactionDate,'Coverage out',0,Amount,Narration FROM dbo.Coverages WHERE FromCorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL UNION ALL SELECT TransactionDate,'Deal in',ToAmount,0,Narration FROM dbo.Deals WHERE ToCorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL UNION ALL SELECT TransactionDate,'Deal out',0,FromAmount,Narration FROM dbo.Deals WHERE FromCorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL UNION ALL SELECT CAST(PaymentDate AS datetime2),'Obligation',0,Amount,Notes FROM dbo.ObligationPayments WHERE CorrespondentAccountId=@CorrespondentAccountId AND DeletedTime IS NULL),f AS(SELECT * FROM e WHERE(@StartDate IS NULL OR EventDate>=@StartDate)AND(@EndDate IS NULL OR EventDate<DATEADD(day,1,CONVERT(date,@EndDate))))SELECT EventDate,EventType,AmountIn,AmountOut,@opening+SUM(AmountIn-AmountOut)OVER(ORDER BY EventDate ROWS UNBOUNDED PRECEDING)RunningBalance,Notes FROM f ORDER BY EventDate;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetCurrencyStatement @CurrencyId uniqueidentifier,@AsOfDate datetime2 AS SELECT a.CorrespondentAccountId,a.AccountNumber,c.CorrespondentNameEn AccountName,a.CurrentBalance,COALESCE((SELECT SUM(r.Amount)FROM dbo.Resources r WHERE r.CorrespondentAccountId=a.CorrespondentAccountId AND r.ResourceDate<=@AsOfDate AND r.DeletedTime IS NULL),0)TotalResources,COALESCE((SELECT SUM(x.Amount)FROM dbo.Coverages x WHERE x.ToCorrespondentAccountId=a.CorrespondentAccountId AND x.TransactionDate<=@AsOfDate AND x.DeletedTime IS NULL),0)TotalCoverageIn,COALESCE((SELECT SUM(x.Amount)FROM dbo.Coverages x WHERE x.FromCorrespondentAccountId=a.CorrespondentAccountId AND x.TransactionDate<=@AsOfDate AND x.DeletedTime IS NULL),0)TotalCoverageOut,COALESCE((SELECT SUM(t.Amount)FROM dbo.Transfers t WHERE t.CorrespondentAccountId=a.CorrespondentAccountId AND t.TransferDate<=@AsOfDate AND t.TransferStatus='Confirmed' AND t.DeletedTime IS NULL),0)TotalConfirmedTransfers,a.CurrentBalance NetBalance FROM dbo.CorrespondentAccounts a JOIN dbo.Correspondents c ON c.CorrespondentId=a.CorrespondentId WHERE a.CurrencyId=@CurrencyId AND a.IsDeleted=0;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetFinalBankPosition @PositionDate date AS BEGIN DECLARE @cash decimal(19,4)=0,@gold decimal(19,4)=0;SELECT TOP(1)@cash=CashInHand,@gold=GoldValue FROM dbo.ReserveSnapshots WHERE ReserveDate<=@PositionDate AND DeletedTime IS NULL ORDER BY ReserveDate DESC,CreatedTime DESC;DECLARE @corr decimal(19,4)=COALESCE((SELECT SUM(CurrentBalance)FROM dbo.CorrespondentAccounts WHERE IsDeleted=0),0);SELECT @PositionDate PositionDate,@cash CashInHandUsd,@gold GoldValueUsd,@corr TotalCorrespondentBalancesUsd,@cash+@gold+@corr BankNetPositionUsd;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetDashboardSummary @AsOfDate date AS BEGIN DECLARE @reserve decimal(19,4)=COALESCE((SELECT TOP(1)GoldValue+CashInHand+Deposits FROM dbo.ReserveSnapshots WHERE ReserveDate<=@AsOfDate AND DeletedTime IS NULL ORDER BY ReserveDate DESC),0);SELECT COALESCE((SELECT SUM(Amount)FROM dbo.Resources WHERE ResourceDate<=@AsOfDate AND DeletedTime IS NULL),0)TotalResourcesUsd,COALESCE((SELECT SUM(Amount)FROM dbo.Transfers WHERE TransferDate<DATEADD(day,1,@AsOfDate)AND TransferStatus='Confirmed'AND DeletedTime IS NULL),0)ConfirmedTransfersUsd,COALESCE((SELECT SUM(CurrentBalance)FROM dbo.CorrespondentAccounts WHERE IsDeleted=0),0)+@reserve NetPositionUsd,(SELECT COUNT(*)FROM dbo.Correspondents WHERE IsDeleted=0 AND IsActive=1)CorrespondentCount,(SELECT COUNT(*)FROM dbo.Transfers WHERE TransferStatus='Pending'AND DeletedTime IS NULL)PendingTransferCount,COALESCE((SELECT SUM(TotalAmount-PaidAmount)FROM dbo.Obligations WHERE DeletedTime IS NULL),0)OutstandingObligationsUsd,@reserve ReserveTotalUsd;END;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetForeignReserveReport @StartDate date,@EndDate date AS SELECT r.ReserveDate ReportDate,COALESCE((SELECT SUM(CurrentBalance)FROM dbo.CorrespondentAccounts WHERE IsDeleted=0),0)CorrespondentBalancesUsd,r.CashInHand CashInHandUsd,r.GoldValue GoldValueUsd,r.Deposits DepositsUsd,COALESCE((SELECT SUM(Amount)FROM dbo.Resources WHERE ResourceDate BETWEEN @StartDate AND @EndDate AND DeletedTime IS NULL),0)ResourcesUsd,COALESCE((SELECT SUM(Amount)FROM dbo.Transfers WHERE TransferDate<DATEADD(day,1,@EndDate)AND TransferDate>=@StartDate AND TransferStatus='Confirmed'AND DeletedTime IS NULL),0)UsagesUsd,COALESCE((SELECT SUM(CurrentBalance)FROM dbo.CorrespondentAccounts WHERE IsDeleted=0),0)+r.CashInHand+r.GoldValue+r.Deposits GrandTotalUsd FROM dbo.ReserveSnapshots r WHERE r.ReserveDate BETWEEN @StartDate AND @EndDate AND r.DeletedTime IS NULL ORDER BY r.ReserveDate;
GO
CREATE OR ALTER PROCEDURE dbo.uspGetObligationReport @StartDate date=NULL,@EndDate date=NULL,@Status nvarchar(20)=NULL AS SELECT o.ObligationId,o.ClientName,c.CurrencyCode,o.TotalAmount,o.PaidAmount,o.TotalAmount-o.PaidAmount RemainingAmount,o.DueDate,CASE WHEN o.PaidAmount>=o.TotalAmount THEN 'Paid' WHEN o.DueDate<CAST(GETUTCDATE()AS date)THEN 'Overdue' ELSE 'Open' END Status FROM dbo.Obligations o JOIN dbo.Currencies c ON c.CurrencyId=o.CurrencyId WHERE o.DeletedTime IS NULL AND(@StartDate IS NULL OR o.ObligationDate>=@StartDate)AND(@EndDate IS NULL OR o.ObligationDate<=@EndDate)AND(@Status IS NULL OR @Status=CASE WHEN o.PaidAmount>=o.TotalAmount THEN 'Paid' WHEN o.DueDate<CAST(GETUTCDATE()AS date)THEN 'Overdue' ELSE 'Open' END)ORDER BY o.DueDate;
