#!/usr/bin/env python3
"""
Export SQL Server stored procedures, views, and functions definitions to text files.

Each object is saved as: Schema/ObjectType--ObjectName.txt

Requires: pyodbc  (pip install pyodbc)
Also requires an installed ODBC driver for SQL Server
(e.g. "ODBC Driver 17 for SQL Server" or "ODBC Driver 18 for SQL Server").
"""

import os
import re
import getpass
import sys

try:
    import pyodbc
except ImportError:
    print("The 'pyodbc' package is required. Install it with:")
    print("    pip install pyodbc")
    sys.exit(1)


QUERY = """
SELECT 
    o.name         AS ObjectName,
    o.type_desc    AS ObjectType,
    s.name         AS SchemaName,
    m.definition   AS Definition
FROM sys.sql_modules m
JOIN sys.objects o ON m.object_id = o.object_id
JOIN sys.schemas s ON o.schema_id = s.schema_id
ORDER BY o.type_desc, o.name;
"""

OUTPUT_FOLDER = "Schema"

# Auto-generated SSMS "Database Diagrams" support procedures - not user code, always skip.
DIAGRAM_PROCS = {
    "sp_alterdiagram",
    "sp_creatediagram",
    "sp_dropdiagram",
    "sp_helpdiagram",
    "sp_helpdiagramdefinition",
    "sp_renamediagram",
    "sp_upgraddiagrams",
}

# Schemas that are entirely auto-generated by SQL Server features (not user code).
EXCLUDED_SCHEMAS = {
    "cdc",  # Change Data Capture - auto-generated capture/cleanup procs and change functions
}

# List of ODBC drivers to try, in order of preference
DRIVER_CANDIDATES = [
    "ODBC Driver 18 for SQL Server",
    "ODBC Driver 17 for SQL Server",
    "ODBC Driver 13 for SQL Server",
    "SQL Server",
]


def pick_driver():
    available = pyodbc.drivers()
    for candidate in DRIVER_CANDIDATES:
        if candidate in available:
            return candidate
    if available:
        # Fall back to the first available SQL Server-ish driver
        return available[0]
    print("No ODBC drivers found on this machine. Please install one, e.g.:")
    print("  'ODBC Driver 17 for SQL Server' or 'ODBC Driver 18 for SQL Server'")
    sys.exit(1)


def sanitize_filename(name: str) -> str:
    """Remove characters that are not safe for filenames."""
    return re.sub(r'[<>:"/\\|?*]', "_", name).strip()


def main():
    print("=== SQL Server Object Exporter (SPs / Views / Functions) ===\n")

    server = input("Server name (e.g. myserver.database.windows.net or SERVER\\INSTANCE): ").strip()
    database = input("Database name: ").strip()
    username = input("SQL username: ").strip()
    password = getpass.getpass("SQL password: ")
    output_folder = input(f"Output folder name [{OUTPUT_FOLDER}]: ").strip() or OUTPUT_FOLDER

    driver = pick_driver()

    conn_str = (
        f"DRIVER={{{driver}}};"
        f"SERVER={server};"
        f"DATABASE={database};"
        f"UID={username};"
        f"PWD={password};"
        f"Encrypt=yes;"
        f"TrustServerCertificate=yes;"
    )

    print(f"\nConnecting to '{server}' / '{database}' using driver '{driver}'...")
    try:
        conn = pyodbc.connect(conn_str, timeout=15)
    except pyodbc.Error as e:
        print("Failed to connect to the database:")
        print(e)
        sys.exit(1)

    print("Connected. Running query...")
    try:
        cursor = conn.cursor()
        cursor.execute(QUERY)
        rows = cursor.fetchall()
    except pyodbc.Error as e:
        print("Failed to run the query:")
        print(e)
        conn.close()
        sys.exit(1)

    print(f"Found {len(rows)} objects. Writing files to './{output_folder}'...\n")

    os.makedirs(output_folder, exist_ok=True)

    written = 0
    skipped = 0

    for row in rows:
        object_name = row.ObjectName
        object_type = row.ObjectType
        schema_name = row.SchemaName
        definition = row.Definition

        if definition is None:
            skipped += 1
            print(f"  [skip] {schema_name}.{object_name} ({object_type}) - no definition (encrypted?)")
            continue

        if object_name.lower() in DIAGRAM_PROCS:
            skipped += 1
            print(f"  [skip] {schema_name}.{object_name} ({object_type}) - SSMS diagram system procedure")
            continue

        if schema_name.lower() in EXCLUDED_SCHEMAS:
            skipped += 1
            print(f"  [skip] {schema_name}.{object_name} ({object_type}) - auto-generated '{schema_name}' schema object")
            continue

        safe_type = sanitize_filename(object_type)
        safe_name = sanitize_filename(object_name)
        safe_schema = sanitize_filename(schema_name)

        filename = f"{safe_type}--{safe_schema}.{safe_name}.txt"
        filepath = os.path.join(output_folder, filename)

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(definition)
            written += 1
        except OSError as e:
            print(f"  [error] Could not write {filepath}: {e}")
            skipped += 1

    conn.close()

    print(f"\nDone. {written} file(s) written, {skipped} skipped.")
    print(f"Output folder: {os.path.abspath(output_folder)}")


if __name__ == "__main__":
    main()
